# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot = {
    initrd.availableKernelModules = [
      "virtio_pci"
      "virtio_scsi"
      "virtio_blk"
    ];
    initrd.kernelModules = [ ];
    kernelModules = [ ];
    extraModulePackages = [ ];
    loader.grub = {
      enable = true;
      device = "/dev/sda";
    };
  };

  fileSystems =
    let
      subvols = builtins.listToAttrs (
        map
          (x: {
            name = "/${x}";
            value = {
              device = "/dev/disk/by-partlabel/disk-main-root";
              fsType = "btrfs";
              options = [
                "subvol=@${x}"
              ]
              ++ (
                if x == "swap" then
                  [ "defaults" ]
                else
                  [
                    "compress-force=zstd"
                    "nosuid"
                    "nodev"
                  ]
              );
            };
          })
          [
            "boot"
            "home"
            "nix"
            "swap"
            "tmp"
            "var"
          ]
      );
    in
    subvols
    // {
      "/" = {
        device = "tmpfs";
        fsType = "tmpfs";
        options = [
          "relatime"
          "mode=755"
          "nosuid"
          "nodev"
        ];
      };
    };

  swapDevices = [ { device = "/swap/swapfile"; } ];

}
