# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/01b02a4c-07c9-40b7-9c33-6c4ca5c38a92";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/4AC2-5EE7";
      fsType = "vfat";
    };

  fileSystems."/storage" =
    {
      device = "/dev/disk/by-uuid/1491a549-90da-4438-9f0b-3beded70cca5";
      fsType = "ext4";
    };

  fileSystems."/storage/substorage" =
    {
      device = "/dev/disk/by-uuid/536af946-d53a-4c4f-aa00-79769b65c22b";
      fsType = "ext4";
    };

  swapDevices = [ ];

  boot.loader = {
    efi.canTouchEfiVariables = false;
    systemd-boot = {
      configurationLimit = 1;
      consoleMode = "auto";
      enable = true;
    };
    timeout = 1;
  };
}
