# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd.availableKernelModules = [
      "xhci_pci"
      "nvme"
      "thunderbolt"
      "usb_storage"
      "usbhid"
      "sd_mod"
    ];
    kernelModules = [ "kvm-amd" ];
    loader = {
      efi.canTouchEfiVariables = false;
      systemd-boot = {
        configurationLimit = 1;
        consoleMode = "auto";
        enable = true;
      };
      timeout = 2;
    };
  };

  fileSystems =
    let
      subvols = builtins.listToAttrs (
        map
          (x: {
            name = x;
            value = {
              device = "/dev/disk/by-label/NixOS";
              fsType = "btrfs";
              options = [
                "compress-force=zstd"
                "nosuid"
                "nodev"
                "subvol=${x}"
              ];
            };
          })
          [
            "/home"
            "/nix"
            "/root"
            "/var"
          ]
      );
    in
    subvols
    // {
      "/" = {
        device = "tmpfs";
        fsType = "tmpfs";
        options = [
          "relatime"
          "mode=755"
          "nosuid"
          "nodev"
        ];
      };

      "/boot" = {
        device = "/dev/disk/by-label/UEFI";
        fsType = "vfat";
        options = [ "umask=0077" ];
      };

    };

  swapDevices = [ ];

  systemd.services.nix-daemon = {
    environment.TMPDIR = "/var/cache/nix";
    serviceConfig.CacheDirectory = "nix";
  };
  environment.variables.NIX_REMOTE = "daemon";

  hardware.amdgpu.initrd.enable = true;

}
