[fcitx5-pinyin-zenith]
src.github = "ZenQy/scel2dict"
fetch.url = "https://github.com/ZenQy/scel2dict/releases/download/$ver/zenith.dict"

[wallpapers]
src.github = "ZenQy/wallpaper"
fetch.url = "https://github.com/ZenQy/wallpaper/releases/download/$ver/wallpaper.tar.gz"

[Ech0]
# src.github = "lin-snow/Ech0"
src.manual = "v5.5.0"
fetch.github = "lin-snow/Ech0"

[Ech0-web]
# src.github = "lin-snow/Ech0"
src.manual = "v5.5.0"
fetch.github = "lin-snow/Ech0"

[linux-flippy]
src.github_tag = "unifreq/linux-6.18.y"
fetch.github = "unifreq/linux-6.18.y"

[einat]
src.github = "EHfive/einat-ebpf"
fetch.github = "EHfive/einat-ebpf"
extract = ["Cargo.lock"]

[rtp2httpd]
src.github = "stackia/rtp2httpd"
fetch.github = "stackia/rtp2httpd"

[freellmapi]
src.github_tag = "tashfeenahmed/freellmapi"
fetch.github = "tashfeenahmed/freellmapi"

[yx-tools]
src.github_tag = "byJoey/yx-tools"
fetch.github = "byJoey/yx-tools"

[sing-box-dashboard]
src.git = "https://github.com/SagerNet/sing-box-dashboard"
src.branch = "gh-pages"
fetch.github = "SagerNet/sing-box-dashboard"

[ampart]
src.github = "7Ji/ampart"
fetch.github = "7Ji/ampart"

[monitor-theme-default]
src.github = "monitor-probe/monitor-theme-default"
fetch.url = "https://github.com/monitor-probe/monitor-theme-default/releases/download/$ver/theme.tar.gz"

[monitor]
src.github = "monitor-probe/monitor"
fetch.github = "monitor-probe/monitor"
extract = ["Cargo.lock"]

[monitor-web-admin]
src.github = "monitor-probe/monitor"
fetch.github = "monitor-probe/monitor"

[monitor-agent]
src.github = "monitor-probe/agent"
fetch.github = "monitor-probe/agent"
extract = ["Cargo.lock"]
