# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  hardware.deviceTree = {
    enable = true;
    name = "meson-sm1-tx3-qz.dtb";
    dtbSource = ./dtb;
  };

  boot = {
    initrd.availableKernelModules = [ "usb_storage" ];
    initrd.kernelModules = [ ];
    kernelModules = [ ];
    extraModulePackages = [ ];
    loader.grub.enable = false;
    loader.generic-extlinux-compatible.enable = true;
    loader.generic-extlinux-compatible.configurationLimit = 2;
    # kernelPackages = pkgs.linuxPackages_latest;
    kernelParams = [
      "audit=0"
      "net.ifnames=0"
      "ipv6.disable=1"
      "consoleblank=0"
      "console=ttyAML0,115200n8"
      "console=tty0"
    ];
  };

  nixpkgs.hostPlatform.system = "aarch64-linux";

  fileSystems."/" = {
    device = "/dev/disk/by-label/ROOTFS_EMMC";
    fsType = "btrfs";
    options = [ "compress-force=zstd" "nosuid" "nodev" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/BOOT_EMMC";
    fsType = "vfat";
    options = [ "umask=0077" ];
  };

  fileSystems."/storage" = {
    device = "/dev/disk/by-label/ADATA";
    fsType = "ext4";
  };

  swapDevices = [ ];

}
