# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ modulesPath, ... }:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot = {
    initrd.availableKernelModules = [
      "ata_piix"
      "uhci_hcd"
      "virtio_pci"
      "virtio_scsi"
      "sd_mod"
    ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
    loader = {
      efi.canTouchEfiVariables = false;
      systemd-boot = {
        configurationLimit = 1;
        consoleMode = "auto";
        enable = true;
      };
      timeout = 1;
    };
  };

  fileSystems =
    let
      subvols = builtins.listToAttrs (
        map
          (x: {
            name = x;
            value = {
              device = "/dev/disk/by-partlabel/disk-main-root";
              fsType = "btrfs";
              options = [
                "compress-force=zstd"
                "nosuid"
                "nodev"
                "subvol=${x}"
              ];
            };
          })
          [
            "/nix"
            "/var"
          ]
      );
    in
    subvols
    // {
      "/" = {
        device = "tmpfs";
        fsType = "tmpfs";
        options = [
          "relatime"
          "mode=755"
          "nosuid"
          "nodev"
        ];
      };

      "/boot" = {
        device = "/dev/disk/by-partlabel/disk-main-boot";
        fsType = "vfat";
        options = [ "umask=0077" ];
      };
    };

  swapDevices = [ { device = "/dev/disk/by-partlabel/disk-main-swap"; } ];
}
