# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/a5105199-637a-428a-99e2-2c6992e19fd6";
      fsType = "ext4";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/eb4db9af-25fc-4dd1-8a97-55f0e9341c9c"; }];

  boot.loader.grub = {
    enable = true;
    device = "/dev/vda";
  };
}
