# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  hardware.deviceTree = {
    enable = true;
    name = "amlogic/meson-gxl-s905d-phicomm-n1.dtb";
    filter = "*phicomm-n1.dtb";
  };

  boot = {
    initrd.availableKernelModules = [ "usb_storage" ];
    initrd.kernelModules = [ ];
    kernelModules = [ ];
    extraModulePackages = [ ];
    loader.grub.enable = false;
    loader.generic-extlinux-compatible.enable = true;
    kernelPackages = pkgs.linuxPackages_latest;
    kernelParams = [
      "audit=0"
      "net.ifnames=0"

      # "root=UUID=ebb01a2b-d47b-43f7-aa46-0a125a8f1d61"
      # "rootfstype=btrfs"
      # "rootflags=compress-force=zstd"

      "consoleblank=0"
      "console=ttyAML0,115200n8"
      "console=tty0"
    ];
  };

  nixpkgs.hostPlatform.system = "aarch64-linux";

  fileSystems."/" = {
    device = "/dev/disk/by-label/ROOTFS_EMMC";
    fsType = "btrfs";
    options = [ "compress-force=zstd" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/BOOT_EMMC";
    fsType = "vfat";
  };

  swapDevices = [ ];

}
