# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ modulesPath, ... }:

{

  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = [
    "ahci"
    "ata_piix"
    "sd_mod"
    "sr_mod"
    "uhci_hcd"
    "virtio_blk"
    "virtio_pci"
    "virtio_scsi"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems =
    let
      subvols = builtins.listToAttrs (
        map
          (x: {
            name = x;
            value = {
              device = "/dev/disk/by-partlabel/disk-main-root";
              fsType = "btrfs";
              options =
                if x == "/swap" then
                  [
                    "defaults"
                    "subvol=${x}"
                  ]
                else
                  [
                    "compress-force=zstd"
                    "nosuid"
                    "nodev"
                    "subvol=${x}"
                  ];
            };
          })
          [
            "/boot"
            "/home"
            "/nix"
            "/swap"
            "/tmp"
            "/var"
          ]
      );
    in
    subvols
    // {
      "/" = {
        device = "tmpfs";
        fsType = "tmpfs";
        options = [
          "relatime"
          "mode=755"
          "nosuid"
          "nodev"
        ];
      };
    };

  swapDevices = [ { device = "/swap/swapfile"; } ];

  boot.loader.grub = {
    enable = true;
    device = "/dev/vda";
  };
}
