# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  Ech0 = {
    pname = "Ech0";
    version = "v5.4.6";
    src = fetchFromGitHub {
      owner = "lin-snow";
      repo = "Ech0";
      rev = "v5.4.6";
      fetchSubmodules = false;
      sha256 = "sha256-nfVA/8ViWcRV8mVGW069tju+iGrYeVlMZ64cvukw+Dw=";
    };
  };
  Ech0-web = {
    pname = "Ech0-web";
    version = "v5.4.6";
    src = fetchFromGitHub {
      owner = "lin-snow";
      repo = "Ech0";
      rev = "v5.4.6";
      fetchSubmodules = false;
      sha256 = "sha256-nfVA/8ViWcRV8mVGW069tju+iGrYeVlMZ64cvukw+Dw=";
    };
  };
  einat = {
    pname = "einat";
    version = "v0.1.11";
    src = fetchFromGitHub {
      owner = "EHfive";
      repo = "einat-ebpf";
      rev = "v0.1.11";
      fetchSubmodules = false;
      sha256 = "sha256-dyjDzg6kpqjcne1Zke2f7KxAJMp2vAbfeyFGXoH+siE=";
    };
    extract = {
      "Cargo.lock" = ./. + "/sha256-dyjDzg6kpqjcne1Zke2f7KxAJMp2vAbfeyFGXoH+siE=/Cargo.lock";
    };
  };
  fcitx5-pinyin-zenith = {
    pname = "fcitx5-pinyin-zenith";
    version = "v2026.07.02";
    src = fetchurl {
      url = "https://github.com/ZenQy/scel2dict/releases/download/v2026.07.02/zenith.dict";
      sha256 = "sha256-1dSmBCEvSGtqfLWHxiR81+uptN+PJC6Eh4wS6MO2GP0=";
    };
  };
  freellmapi = {
    pname = "freellmapi";
    version = "v0.6.5";
    src = fetchFromGitHub {
      owner = "tashfeenahmed";
      repo = "freellmapi";
      rev = "v0.6.5";
      fetchSubmodules = false;
      sha256 = "sha256-IyAycr7mzyfUaM9VvQn4Le5nARstcPw0+cpbbAWPmws=";
    };
  };
  komari = {
    pname = "komari";
    version = "1.3.2";
    src = fetchFromGitHub {
      owner = "komari-monitor";
      repo = "komari";
      rev = "1.3.2";
      fetchSubmodules = false;
      sha256 = "sha256-6pw/DeG1kn3J+cIqY5w/R70O9s70MlcQwd8nVlRMoA4=";
    };
  };
  komari-web = {
    pname = "komari-web";
    version = "1.3.2";
    src = fetchFromGitHub {
      owner = "komari-monitor";
      repo = "komari-web";
      rev = "1.3.2";
      fetchSubmodules = false;
      sha256 = "sha256-wAahCOfAh5nlN6qhdiul6MZTCfIygsFLENgrfY2yAew=";
    };
  };
  linux-flippy = {
    pname = "linux-flippy";
    version = "v6.18.38";
    src = fetchFromGitHub {
      owner = "unifreq";
      repo = "linux-6.18.y";
      rev = "v6.18.38";
      fetchSubmodules = false;
      sha256 = "sha256-4x1MdsUNm/3+DM0SSKH3/DFe7328SDjULvPAhisnRZE=";
    };
  };
  rtp2httpd = {
    pname = "rtp2httpd";
    version = "v3.15.3";
    src = fetchFromGitHub {
      owner = "stackia";
      repo = "rtp2httpd";
      rev = "v3.15.3";
      fetchSubmodules = false;
      sha256 = "sha256-IybbEUN4V7jmCUkpYKf9CIMzZickWK3TB4m2GbOE8XE=";
    };
  };
  wallpapers = {
    pname = "wallpapers";
    version = "v2026.07.03";
    src = fetchurl {
      url = "https://github.com/ZenQy/wallpaper/releases/download/v2026.07.03/wallpaper.tar.gz";
      sha256 = "sha256-yRdKo5+k2C6j0aZbntsRe30tIk6qCS9iOiWU5N+EjEM=";
    };
  };
  yx-tools = {
    pname = "yx-tools";
    version = "v2.2.7";
    src = fetchFromGitHub {
      owner = "byJoey";
      repo = "yx-tools";
      rev = "v2.2.7";
      fetchSubmodules = false;
      sha256 = "sha256-neYhk/ZIyKuE5yCWPhXrdREy1OMMWz39oHiiEQUOzyY=";
    };
  };
}
