# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd.availableKernelModules = [
      "xhci_pci"
      "nvme"
      "thunderbolt"
      "usb_storage"
      "usbhid"
      "sd_mod"
    ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
  };

  fileSystems."/" = {
    device = "tmpfs";
    fsType = "tmpfs";
    options = [
      "relatime"
      "mode=755"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-label/NixOS";
    fsType = "btrfs";
    options = [
      "compress-force=zstd"
      "nosuid"
      "nodev"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/UEFI";
    fsType = "vfat";
    options = [ "umask=0077" ];
  };

  swapDevices = [ ];

  environment.persistence."/nix/persistent" = {
    hideMounts = true;

    directories = [
      # "/home/nixos"
      "/var/cache"
      "/var/lib"
      "/var/log"
      "/root/.ssh"
    ];

    files = [
      "/etc/machine-id"
    ];

    users.nixos = {
      directories = [
        # 个人文件
        "Desktop"
        "Documents"
        "Downloads"
        "Music"
        "Pictures"
        "Videos"
        "go"

        # 配置文件夹
        ".cache"
        ".config"
        ".local"
        ".mozilla"
        ".ssh"
      ];
      files = [
        ".bash_history"
      ];
    };
  };

  systemd.services.nix-daemon = {
    environment = {
      TMPDIR = "/var/cache/nix";
    };
    serviceConfig = {
      CacheDirectory = "nix";
    };
  };
  environment.variables.NIX_REMOTE = "daemon";

  services.pipewire = {
    enable = true;
    alsa.enable = true;
    pulse.enable = true;
  };
  # services.xserver.videoDrivers = [ "amdgpu" ];

  hardware.amdgpu.initrd.enable = true;

  boot.loader = {
    efi.canTouchEfiVariables = false;
    systemd-boot = {
      configurationLimit = 1;
      consoleMode = "auto";
      enable = true;
    };
    timeout = 2;
  };
}
