name: Remote Build for vps
on:
  schedule:
    - cron: 0 20 1/16 * *
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled"
        required: false
        default: false

env:
  NIX_PATH: nixpkgs=channel:nixos-unstable
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        hosts:
          - osaka-1
          - osaka-2
          - claw
          - natvps
          - alice
          - sailor
          - legend

    steps:
      - name: Delete older workflow runs and artifacts
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 3
          keep_minimum_runs: 3

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: SSH Private Key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install nixFlake
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            trusted-public-keys = zenqy.cachix.org-1:G5csLBsu/kQIOXU7XUiqeMacwzN1WQWv0+GysTVmJgo= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://zenqy.cachix.org/ https://cache.nixos.org/

      - name: Magic Nix Cache
        uses: DeterminateSystems/flakehub-cache-action@main

      - name: Use Cachix
        uses: cachix/cachix-action@v16
        with:
          name: zenqy
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Environment Prepare
        run: |
          host=$(echo ${{ matrix.hosts }} | sed 's/-/_/g' | awk '{print toupper ($0)}')
          echo HOST=$host >> $GITHUB_ENV
          nix-env -f '<nixpkgs>' -iA nixos-rebuild

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

      - id: set-ipv6
        name: Set IPv6 tag
        run: |
          host=${{matrix.hosts}}
          if [[ $host == 'alice' || $host == 'natvps' || $host == 'legend' ]]; then
            echo "ipv6=true" >> $GITHUB_OUTPUT
          fi

      - name: Set up WARP
        if: ${{ steps.set-ipv6.outputs.ipv6 == 'true' }}
        uses: fscarmen/warp-on-actions@v1.3
        with:
          stack: ipv6
          mode: client

      - name: remote build
        env:
          NIX_SSHOPTS: "-o StrictHostKeyChecking=no -p 2022"
        run: |
          nixos-rebuild switch --flake .#${{ matrix.hosts }} --target-host root@${{ secrets[env.HOST] }}

      - name: executing remote ssh commands using ssh key
        if: ${{ steps.set-ipv6.outputs.ipv6 == 'true' }}
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets[env.HOST] }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          protocol: tcp6
          port: "2022"
          script: nix-collect-garbage -d

      - name: executing remote ssh commands using ssh key
        if: ${{ steps.set-ipv6.outputs.ipv6 != 'true' }}
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets[env.HOST] }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: "2022"
          script: nix-collect-garbage -d

      - name: Telegram notification
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            [${{ matrix.hosts }}]编译失败，请查明原因
