name: Remote Build for vps
on:
  schedule:
    - cron: 0 20 1/16 * *
  workflow_dispatch:
    inputs:
      hosts:
        type: choice
        description: "choose one or all vps"
        options:
          - all
          - beelink
          - gcloud
          - osaka-1
          - osaka-2
          - sailor
          - wawo
          - yuusei
        required: true
        default: all
      command:
        type: choice
        description: "choose the command"
        options:
          - boot
          - switch
          - test
        required: true
        default: boot

env:
  NIX_PATH: nixpkgs=channel:nixos-unstable
  TZ: Asia/Shanghai

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Delete older workflow runs and artifacts
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 3
          keep_minimum_runs: 3
      - id: set-matrix
        name: set-matrix
        run: |
          hosts='[ "${{ inputs.hosts }}" ]'
          if [[ "${{ inputs.hosts }}" == 'all' || "${{ inputs.hosts }}" == '' ]]; then
            hosts='[ "osaka-1", "osaka-2", "yuusei", "sailor", "wawo", "gcloud"]'
          fi
          echo $hosts
          echo "matrix=$(echo $hosts)" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        hosts: ${{ fromJSON(needs.prepare.outputs.matrix) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: SSH Private Key
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install nixFlake
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            trusted-public-keys = zenqy.cachix.org-1:G5csLBsu/kQIOXU7XUiqeMacwzN1WQWv0+GysTVmJgo= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://zenqy.cachix.org/ https://cache.nixos.org/

      - name: Magic Nix Cache
        uses: DeterminateSystems/flakehub-cache-action@main

      - name: Use Cachix
        uses: cachix/cachix-action@v17
        with:
          name: zenqy
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          useDaemon: false

      - name: Environment Prepare
        run: |
          command="${{ inputs.command }}"
          if [[ -z "$command" ]]; then
            command="boot"
          fi
          echo "CMD=$command" >> $GITHUB_ENV
          host=$(echo ${{ matrix.hosts }} | sed 's/-/_/g' | awk '{print toupper ($0)}')
          echo "HOST=$host" >> $GITHUB_ENV
          protocol="tcp"
          host=${{ matrix.hosts }}
          if [[ "$host" == 'yuusei' ]]; then
            protocol="tcp6"
            echo "PROTOCOL=$protocol" >> $GITHUB_ENV
          fi
          nix-env -f '<nixpkgs>' -iA nixos-rebuild

      - name: Set up WARP
        if: ${{ env.PROTOCOL == 'tcp6' }}
        uses: fscarmen/warp-on-actions@v1.4
        with:
          stack: ipv6
          mode: client

      - name: remote build
        env:
          NIX_SSHOPTS: "-o StrictHostKeyChecking=no -p ${{ secrets.PORT }}"
        run: |
          host=${{ matrix.hosts }}
          ip=${{ secrets[env.HOST] }}
          if [[ "${{ env.PROTOCOL }}" == "tcp6" ]]; then
            ip="[$ip]"
          fi

          if [[ "$host" == 'beelink' ]]; then
            nixos-rebuild build --flake .#$host --target-host root@$ip
          else
            nixos-rebuild ${{ env.CMD }} --flake .#$host --target-host root@$ip
          fi

      - name: executing remote ssh commands using ssh key
        if: ${{ matrix.hosts != 'beelink' }}
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets[env.HOST] }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          protocol: ${{ env.PROTOCOL }}
          port: ${{ secrets.PORT }}
          script: |
            nix-collect-garbage -d
            if [[ "${{ env.CMD }}" == 'boot' ]]; then
              reboot
            fi

      - name: Telegram notification
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            [${{ matrix.hosts }}]编译失败，请查明原因
