name: Build for arm64
on:
  workflow_dispatch:
env:
  NIX_PATH: nixpkgs=channel:nixos-unstable
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Install nixFlake
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            trusted-public-keys = zenqy.cachix.org-1:G5csLBsu/kQIOXU7XUiqeMacwzN1WQWv0+GysTVmJgo= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://zenqy.cachix.org/ https://cache.nixos.org/

      - name: Magic Nix Cache
        uses: DeterminateSystems/flakehub-cache-action@main

      - name: Use Cachix
        uses: cachix/cachix-action@v17
        with:
          name: zenqy
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          useDaemon: false

      - name: remote build
        run: |
          nix-env -f '<nixpkgs>' -iA nixos-rebuild
          nixos-rebuild build --flake .#e20c
          nixos-rebuild build --flake .#rock-5b
          nixos-rebuild build --flake .#oect
